<template>
  <scroll-view class="ach_doc">
    <dpmsTable firstLinefixed :contents="contents" />
  </scroll-view>
</template>

<script>
import moment from 'moment'
import loadMore from '@/components/load-more/load-more.vue'

const theUrl = '/pages/demos/noticeBar-demo/more' // 本地的某个页面
const httpUrl = 'https://ext.dcloud.net.cn/plugin?id=2667' // 某个网址

export default {
  components: {
    loadMore,
  },
  data() {
    return {
      contents: [
        {
          name: '刘一',
          age: '',
          collage: '信息学院',
          score: '99',
          url: ['查看更多', theUrl],
          link: '',
        },
        {
          name: '陈二',
          age: '18',
          collage: '商学院',
          score: '98',
          url: ['我带参数', theUrl, { name: '陈二' }],
          link: '',
        },
        {
          name: '张三',
          age: '22',
          collage: '统计与数学学院',
          score: '97',
          url: ['查看更多', theUrl],
          link: '',
        },
        {
          name: '李四',
          age: '19',
          collage: '城市与环境学院',
          score: '96',
          url: '',
          link: ['访问网址', httpUrl],
        },
        {
          name: '王五',
          age: '20',
          collage: '旅游与酒店管理学院',
          score: '95',
          url: ['查看更多', theUrl],
          link: '',
        },
        {
          name: '赵六 ',
          age: '20',
          collage: '',
          score: '88',
          url: ['查看更多', theUrl],
          link: '',
        },
        {
          name: '孙七',
          age: '21',
          collage: '',
          score: '95',
          url: '',
          link: ['访问网址', httpUrl],
        },
        {
          name: '周八 ',
          age: '21',
          collage: '会计学院',
          score: '85',
          url: ['查看更多', theUrl],
          link: '',
        },
        {
          name: '吴九 ',
          age: '20',
          collage: '',
          score: '91',
          url: ['查看更多', theUrl],
          link: '',
        },
        {
          name: '郑十',
          age: '19',
          collage: '',
          score: '95',
          url: '',
          link: ['访问网址', httpUrl],
        },
        {
          name: '刘一',
          age: '',
          collage: '信息学院',
          score: '99',
          url: ['查看更多', theUrl],
          link: '',
        },
        {
          name: '陈二',
          age: '18',
          collage: '商学院',
          score: '98',
          url: ['我带参数', theUrl, { name: '陈二' }],
          link: '',
        },
        {
          name: '张三',
          age: '22',
          collage: '统计与数学学院',
          score: '97',
          url: ['查看更多', theUrl],
          link: '',
        },
        {
          name: '李四',
          age: '19',
          collage: '城市与环境学院',
          score: '96',
          url: '',
          link: ['访问网址', httpUrl],
        },
        {
          name: '王五',
          age: '20',
          collage: '旅游与酒店管理学院',
          score: '95',
          url: ['查看更多', theUrl],
          link: '',
        },
        {
          name: '赵六 ',
          age: '20',
          collage: '',
          score: '88',
          url: ['查看更多', theUrl],
          link: '',
        },
        {
          name: '孙七',
          age: '21',
          collage: '',
          score: '95',
          url: '',
          link: ['访问网址', httpUrl],
        },
        {
          name: '周八 ',
          age: '21',
          collage: '会计学院',
          score: '85',
          url: ['查看更多', theUrl],
          link: '',
        },
        {
          name: '吴九 ',
          age: '20',
          collage: '',
          score: '91',
          url: ['查看更多', theUrl],
          link: '',
        },
        {
          name: '郑十',
          age: '19',
          collage: '',
          score: '95',
          url: '',
          link: ['访问网址', httpUrl],
        },
      ],
      total: 0,
      current: 0,
    }
  },
  onLoad() {
    this.init()
  },
  onReachBottom() {
    // if (this.contents.length < this.total) {
    this.current += 1
    this.getDoctors()
    // }
  },
  methods: {
    init() {
      this.current = 1
      this.getDoctors()
    },
    getDoctors() {
      const data = {
        current: 1,
        hitCount: false,
        orders: [],
        pages: 3,
        records: [
          {
            birthday: '',
            contactLabel: -1,
            doctorStaffId: 10042,
            doctorStaffName: '测试报表权限',
            gender: 3,
            institutionDepartmentId: 1532,
            institutionDepartmentName: '测试科室',
            medicalRecordNo: '2021012364649',
            memo:
              '转诊挂号，转诊自刘书兰2，挂号时间：2021-03-26 13:50 转诊操作时间：2021-03-26 13:50',
            mobile: '11458172045',
            oldDoctorStaffId: 1645,
            oldDoctorStaffName: '刘书兰2',
            oldInstitutionDepartmentId: -1,
            oldInstitutionDepartmentName: '未指定科室',
            patientName: 'bob测试划扣2',
            payAmount: 0,
            referralStatisticsId: 520,
            referralTime: 1616737833000,
            registerId: 286195,
            registerTime: 1616737828000,
            statRegisterDate: 1616688000000,
            visType: 2,
          },
          {
            birthday: '2021-02-18',
            contactLabel: -1,
            doctorStaffId: 10042,
            doctorStaffName: '测试报表权限',
            gender: 2,
            institutionDepartmentId: 1532,
            institutionDepartmentName: '测试科室',
            medicalRecordNo: '2021021864687',
            memo:
              '转诊挂号，转诊自刘书兰2，挂号时间：2021-03-26 13:49 转诊操作时间：2021-03-26 13:49',
            mobile: '13453212443',
            oldDoctorStaffId: 1645,
            oldDoctorStaffName: '刘书兰2',
            oldInstitutionDepartmentId: -1,
            oldInstitutionDepartmentName: '未指定科室',
            patientName: '庄周2',
            payAmount: 0,
            referralStatisticsId: 519,
            referralTime: 1616737791000,
            registerId: 286194,
            registerTime: 1616737784000,
            statRegisterDate: 1616688000000,
            visType: 2,
          },
          {
            birthday: '2021-02-18',
            contactLabel: -1,
            doctorStaffId: -1,
            doctorStaffName: '未指定医生',
            gender: 2,
            institutionDepartmentId: -1,
            institutionDepartmentName: '未指定科室',
            medicalRecordNo: '2021021864687',
            memo:
              '转诊挂号，转诊自刘书兰2，挂号时间：2021-03-26 10:51 转诊操作时间：2021-03-26 10:51',
            mobile: '13453212443',
            oldDoctorStaffId: 1645,
            oldDoctorStaffName: '刘书兰2',
            oldInstitutionDepartmentId: -1,
            oldInstitutionDepartmentName: '未指定科室',
            patientName: '庄周2',
            payAmount: 0,
            referralStatisticsId: 518,
            referralTime: 1616727090000,
            registerId: 286190,
            registerTime: 1616727088000,
            statRegisterDate: 1616688000000,
            visType: 2,
          },
          {
            birthday: '2021-02-18',
            contactLabel: -1,
            doctorStaffId: 3232,
            doctorStaffName: '兰兰口腔',
            gender: 2,
            institutionDepartmentId: 667,
            institutionDepartmentName: '口腔科',
            medicalRecordNo: '2021021864687',
            memo:
              '转诊挂号，转诊自刘书兰2，挂号时间：2021-03-26 10:49 转诊操作时间：2021-03-26 10:49',
            mobile: '13453212443',
            oldDoctorStaffId: 1645,
            oldDoctorStaffName: '刘书兰2',
            oldInstitutionDepartmentId: -1,
            oldInstitutionDepartmentName: '未指定科室',
            patientName: '庄周2',
            payAmount: 0,
            referralStatisticsId: 517,
            referralTime: 1616726973000,
            registerId: 286189,
            registerTime: 1616726965000,
            statRegisterDate: 1616688000000,
            visType: 2,
          },
          {
            birthday: '',
            contactLabel: -1,
            doctorStaffId: 1721,
            doctorStaffName: '安医生',
            gender: 3,
            institutionDepartmentId: -1,
            institutionDepartmentName: '未指定科室',
            medicalRecordNo: '2021012364649',
            memo:
              '转诊挂号，转诊自刘书兰2，挂号时间：2021-03-26 10:49 转诊操作时间：2021-03-26 10:49',
            mobile: '11458172045',
            oldDoctorStaffId: 1645,
            oldDoctorStaffName: '刘书兰2',
            oldInstitutionDepartmentId: -1,
            oldInstitutionDepartmentName: '未指定科室',
            patientName: 'bob测试划扣2',
            payAmount: 0,
            referralStatisticsId: 516,
            referralTime: 1616726962000,
            registerId: 286188,
            registerTime: 1616726957000,
            statRegisterDate: 1616688000000,
            visType: 2,
          },
          {
            birthday: '',
            contactLabel: -1,
            doctorStaffId: 9994,
            doctorStaffName: '个人权限',
            gender: 3,
            institutionDepartmentId: 667,
            institutionDepartmentName: '口腔科',
            medicalRecordNo: '2021012364649',
            memo:
              '转诊挂号，转诊自刘书兰2，挂号时间：2021-03-26 10:49 转诊操作时间：2021-03-26 10:49',
            mobile: '11458172045',
            oldDoctorStaffId: 1645,
            oldDoctorStaffName: '刘书兰2',
            oldInstitutionDepartmentId: -1,
            oldInstitutionDepartmentName: '未指定科室',
            patientName: 'bob测试划扣2',
            payAmount: 0,
            referralStatisticsId: 515,
            referralTime: 1616726955000,
            registerId: 286187,
            registerTime: 1616726950000,
            statRegisterDate: 1616688000000,
            visType: 2,
          },
          {
            birthday: '',
            contactLabel: -1,
            doctorStaffId: 10042,
            doctorStaffName: '测试报表权限',
            gender: 3,
            institutionDepartmentId: 1532,
            institutionDepartmentName: '测试科室',
            medicalRecordNo: '2021012364649',
            memo:
              '转诊挂号，转诊自刘书兰2，挂号时间：2021-03-26 10:33 转诊操作时间：2021-03-26 10:33',
            mobile: '11458172045',
            oldDoctorStaffId: 1645,
            oldDoctorStaffName: '刘书兰2',
            oldInstitutionDepartmentId: -1,
            oldInstitutionDepartmentName: '未指定科室',
            patientName: 'bob测试划扣2',
            payAmount: 0,
            referralStatisticsId: 514,
            referralTime: 1616726027000,
            registerId: 286183,
            registerTime: 1616726020000,
            statRegisterDate: 1616688000000,
            visType: 2,
          },
          {
            birthday: '2020-07-01',
            contactLabel: -1,
            doctorStaffId: 2429,
            doctorStaffName: '吴相德 医生勿动',
            gender: 2,
            institutionDepartmentId: -1,
            institutionDepartmentName: '未指定科室',
            medicalRecordNo: 'BL202007090051',
            memo:
              '转诊挂号，转诊自测试报表权限，挂号时间：2021-03-25 21:26 转诊操作时间：2021-03-25 21:26',
            mobile: '13567898763',
            oldDoctorStaffId: 10042,
            oldDoctorStaffName: '测试报表权限',
            oldInstitutionDepartmentId: -1,
            oldInstitutionDepartmentName: '未指定科室',
            patientName: '杰西卡2',
            payAmount: 0,
            referralStatisticsId: 475,
            referralTime: 1616678830000,
            registerId: 286174,
            registerTime: 1616678810000,
            statRegisterDate: 1616601600000,
            visType: 1,
          },
          {
            birthday: '2011-07-04',
            doctorStaffId: 2429,
            doctorStaffName: '吴相德 医生勿动',
            gender: 2,
            institutionDepartmentId: -1,
            institutionDepartmentName: '未指定科室',
            medicalRecordNo: 'BL202007080005',
            memo:
              '转诊挂号，转诊自测试报表权限，挂号时间：2021-03-25 21:18 转诊操作时间：2021-03-25 21:18',
            oldDoctorStaffId: 10042,
            oldDoctorStaffName: '测试报表权限',
            oldInstitutionDepartmentId: -1,
            oldInstitutionDepartmentName: '未指定科室',
            patientName: '新宝宝',
            payAmount: 0,
            referralStatisticsId: 474,
            referralTime: 1616678322000,
            registerId: 286169,
            registerTime: 1616678307000,
            statRegisterDate: 1616601600000,
            visType: 1,
          },
          {
            birthday: '',
            contactLabel: -1,
            doctorStaffId: 1645,
            doctorStaffName: '刘书兰2',
            gender: 3,
            institutionDepartmentId: 788,
            institutionDepartmentName: '牙科',
            medicalRecordNo: '2021012364649',
            memo:
              '转诊挂号，转诊自测试报表权限，挂号时间：2021-03-25 17:39 转诊操作时间：2021-03-25 17:39',
            mobile: '11458172045',
            oldDoctorStaffId: 10042,
            oldDoctorStaffName: '测试报表权限',
            oldInstitutionDepartmentId: -1,
            oldInstitutionDepartmentName: '未指定科室',
            patientName: 'bob测试划扣2',
            payAmount: 0,
            referralStatisticsId: 470,
            referralTime: 1616665170000,
            registerId: 286141,
            registerTime: 1616665155000,
            statRegisterDate: 1616601600000,
            visType: 2,
          },
        ],
        searchCount: true,
        size: 10,
        total: 25,
      }
      if (this.current === 1) {
      } else {
        console.log(this.contents)
        this.contents = this.contents.concat(data.records)
      }
      this.total = 100
    },
  },
}
</script>

<style lang="scss" scoped>
.ach_doc {
  width: 100%;
}
</style>
